---
- name: ensure nonlocal binding allowed
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: true
    file: /etc/sysctl.d/haproxy.conf
    reload: true
    state: present

- name: ensure IP forwarding allowed
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: true
    file: /etc/sysctl.d/haproxy.conf
    reload: true
    state: present

- name: configure rsyslog to listen on UDP socket
  blockinfile:
    path: /etc/rsyslog.conf
    insertafter: '# Provides UDP syslog reception'
    marker: "# {mark} DS MANAGED BLOCK (proxy)"
    block: |
      $ModLoad imudp
      $UDPServerRun 514
      $UDPServerAddress 127.0.0.1
  notify:
    - restart syslog

- name: place rsyslog config for HAProxy
  copy:
    src: rsyslog-haproxy.conf
    dest: /etc/rsyslog.d
  notify:
    - restart syslog

- name: place logrotate config for HAProxy
  copy:
    src: logrotate-haproxy
    dest: /etc/logrotate.d

- name: ensure CentOS 7 stock HAProxy is not installed
  package:
    name: haproxy
    state: absent

- name: ensure Software Collections repository is installed
  package:
    name: centos-release-scl

- name: ensure HAProxy version 1.8 is installed
  package:
    name: "{{ item }}"
  with_items:
    - rh-haproxy18-haproxy
    - rh-haproxy18-haproxy-syspaths

- name: ensure HAProxy starts on reboot
  service:
    name: rh-haproxy18-haproxy
    enabled: true
    state: started
