---
- name: cyverse.irods-cfg
  src: https://github.com/CyVerse-Ansible/ansible-irods-cfg
  version: bd98d427b1d31a41f1f1bd4c513cde8001c9c529

- name: cyverse.rabbitmq-vhost
  src: CyVerse-Ansible.rabbitmq-vhost

- name: uoi-io.haproxy
  src: uoi-io.haproxy
