---
- name: cyverse.irods-cfg
  src: https://github.com/CyVerse-Ansible/ansible-irods-cfg
  version: 0795fa6a60f554c26ce7569929bec4f426345cc9

- name: cyverse.rabbitmq-vhost
  src: cyverse-ansible.rabbitmq-vhost

- name: geerlingguy.apache
  src: geerlingguy.apache

- name: uoi-io.haproxy
  src: uoi-io.haproxy
