---
_nic_mtu: "{{ nic_mtu if nic_mtu is defined else None }}"
_nic_txqueuelen: "{{ nic_txqueuelen if nic_txqueuelen is defined else None }}"

_rebootable: "{{ rebootable if rebootable is defined else true }}"

_sysctl_net: "{{ sysctl_net if sysctl_net is defined else [] }}"

_update_e2fsprogs: "{{ update_e2fsprogs if update_e2fsprogs is defined else true }}"
