---
version: "2.0"

services:
  amqp:
    image: rabbitmq:3.5-management
    hostname: amqp

  dbms:
    build:
      context: dbms
      args:
        IRODS_RESOURCE_SERVER: rs-centos6
    hostname: dbms
    tty: true

  ies:
    build:
      context: ies
      args:
        IRODS_LAST_EPHEMERAL_PORT: 20009
        IRODS_SCHEMA_VALIDATION: "off"
    hostname: ies
    tty: true
    links:
      - amqp
      - dbms

  rs_centos6:
    build:
      context: rs
      dockerfile: Dockerfile.centos6
      args:
        IRODS_HOST: rs-centos6
        IRODS_LAST_EPHEMERAL_PORT: 20009
        IRODS_SCHEMA_VALIDATION: "off"
    hostname: rs-centos6
    tty: true
    links:
      - amqp
      - ies
