---
version: "2.0"

services:
  amqp:
    image: rabbitmq:3.5-management
    hostname: amqp

  dbms:
    build:
      context: dbms
    hostname: dbms
    tty: true

  ies:
    build:
      context: ies
      args:
        IRODS_LAST_EPHEMERAL_PORT: 20009
        IRODS_SCHEMA_VALIDATION: "off"
    hostname: ies
    tty: true
    links:
      - amqp
      - dbms

  rs:
    build:
      context: rs
      args:
        IRODS_LAST_EPHEMERAL_PORT: 20009
        IRODS_SCHEMA_VALIDATION: "off"
    hostname: rs
    tty: true
    links:
      - amqp
      - ies
