---
version: "2.0"

services:
  amqp:
    image: rabbitmq:3.5-management
    hostname: amqp

  ansible:
    build:
      context: ansible
    hostname: ansible
    tty: true
    volumes:
      - ./inventory:/inventory
      - ./playbook.yml:/playbook.yml
    depends_on:
      - amqp
      - dbms
      - ies
      - rs_centos6
      - rs_centos7

  dbms:
    build:
      context: dbms
      args:
        IRODS_RESOURCES: "rs_centos6:rs_centos6:/var/lib/irods/Vault rs_centos7:rs_centos7:/var/lib/irods/Vault"
    hostname: dbms
    tty: true

  ies:
    build:
      context: ies
      args:
        IRODS_DEFAULT_RESOURCE: rs_centos6
        IRODS_LAST_EPHEMERAL_PORT: 20009
        IRODS_SCHEMA_VALIDATION: "off"
    hostname: ies
    tty: true
    depends_on:
      - amqp
      - dbms

  rs_centos6:
    build:
      context: rs
      dockerfile: Dockerfile.centos6
      args:
        IRODS_HOST: rs_centos6
        IRODS_LAST_EPHEMERAL_PORT: 20009
        IRODS_LOCAL_RESOURCE: rs_centos6
        IRODS_SCHEMA_VALIDATION: "off"
    hostname: rs_centos6
    tty: true
    depends_on:
      - ies

  rs_centos7:
    build:
      context: rs
      dockerfile: Dockerfile.centos7
      args:
        IRODS_HOST: rs_centos7
        IRODS_LAST_EPHEMERAL_PORT: 20009
        IRODS_LOCAL_RESOURCE: rs_centos7
        IRODS_SCHEMA_VALIDATION: "off"
    hostname: rs_centos7
    tty: true
    depends_on:
      - ies
