---
ansible_port: 1657

rebootable: true
update_e2fsprogs: true

# System configuration

nic_mtu: null
nic_txqueuelen: null
sysctl_net: []


# rabbitmq configuration

rabbitmq_port: 31333
rabbitmq_user: ipc
rabbitmq_password: mostly810S
rabbitmq_vhost: /de-2/data-store
rabbitmq_ephemeral: false


# iRODS configuration

default_number_of_transfer_threads: 16
parallel_transfer_buffer_size: 32

aegis_resources: []

iclimate_resources: []

single_threaded_resources: []

dbms_port: 31398
dbms_username: irods
dbms_password: SillyBilly

negotiation_key: 'D^a!lP2+Kv+zZFnR1S7xsIh5y7Rff89X'

server_control_plane_key: zcDxUM9S57Wf22B8wwAMrwpBtwsBBZff
server_port_range_start: 20000
server_port_range_end: 20099

zone_key: P3SDF2SWQR22sMs7drCgtcxYDUxL6JDjqsJDM6FMAzUkdHpaf

sernec_owners: []
sernec_writers: []
sernec_readers: []

irods_version: 4.1.10
irods_service_account_name: irods
irods_service_group_name: irods
irods_port: 1247
irods_zone: iplant
irods_clerver_user: rods
irods_clerver_password: SillyBilly
irods_default_resource: demoResc
irods_resources: []
