---
- name: install HAPRoxy
  hosts: load_balancer
  become: true
  roles:
    - role: uoi-io.haproxy
      vars:
        haproxy_firewalld: false
        haproxy_selinux: false
        haproxy_global_cpu_maps:
          - 1 0
        haproxy_global_nbproc: 1
        haproxy_global_tunes: []
        haproxy_default_errorfiles: []
        haproxy_default_mode: tcp
        haproxy_default_options:
          - clitcpka
          - dontlognull
          - tcplog
        haproxy_default_timeouts:
          - connect 10s
          - client 1d
          - client-fin 2m
          - queue 10m
          - server 1d
          - server-fin 2m
        haproxy_stats: true
        haproxy_stats_address: '*'
        haproxy_stats_port: 9001
        haproxy_stats_uri: /
        haproxy_stats_user: haproxy-stats
        haproxy_stats_password: password
        haproxy_stats_options:
          - refresh 20s
          - show-legends
          - show-node
          - hide-version
        haproxy_listen:
          - irods:
              binds:
                - "*:{{ _load_balancer_irods_proxy_port }}"
              servers:
                - "{{ groups['ies'][0] }} {{ lookup('dig', groups['ies'][0]) }}:1247 maxconn 50"
      notify:
        - reload haproxy

  pre_tasks:
    - name: configure rsyslog to listen on UDP socket
      blockinfile:
        path: /etc/rsyslog.conf
        insertafter: '# Provides UDP syslog reception'
        block: |
          $ModLoad imudp
          $UDPServerRun 514
          $UDPServerAddress 127.0.0.1
      notify:
        - restart syslog

    - name: place rsyslog config for haproxy
      copy:
        src: files/haproxy.conf
        dest: /etc/rsyslog.d
      notify:
        - restart syslog

  post_tasks:
    - name: open iRODS proxy port
      blockinfile:
        path: /etc/sysconfig/iptables
        insertbefore: -A INPUT -j REJECT
        marker: "# {mark} DS MANAGED BLOCK (load_balancer)"
        content: |
          -A INPUT -m state --state NEW -p tcp -s {{ _load_balancer_irods_allowed_src }} --dport {{ _load_balancer_irods_proxy_port }} -j ACCEPT
          -A INPUT -m state --state NEW -p tcp -s 128.196.38.31 --dport 9001 -j ACCEPT
      notify:
        - restart firewall

  handlers:
    - name: reload haproxy
      service:
        name: haproxy
        state: reloaded

    - name: restart firewall
      service:
        name: iptables
        state: restarted

    - name: restart syslog
      service:
        name: rsyslog
        state: restarted

  tags:
    - no_testing
