---
- name: install HAPRoxy
  hosts: load_balancer
  become: true
  roles:
    - role: uoi-io.haproxy
      vars:
        haproxy_firewalld: false
        haproxy_selinux: false
        haproxy_global_cpu_maps:
          - 1 0
        haproxy_global_nbproc: 1
        haproxy_global_tunes: []
        haproxy_default_errorfiles: []
        haproxy_default_maxconn: 50
        haproxy_default_mode: tcp
        haproxy_default_options:
          - clitcpka
          - dontlognull
          - tcplog
        haproxy_default_timeouts:
          - connect 10s
          - client 2h
          - server 2h
          - queue 2m
        haproxy_stats: false
        haproxy_listen:
          - irods:
              binds:
                - "*:{{ load_balancer_irods_proxy_port }}"
              servers:
                - "{{ groups['ies'][0] }} {{ lookup('dig', groups['ies'][0]) }}:1247"
      notify:
        - reload haproxy

  pre_tasks:
    - name: configure rsyslog to listen on UDP socket
      blockinfile:
        path: /etc/rsyslog.conf
        insertafter: '# Provides UDP syslog reception'
        block: |
          $ModLoad imudp
          $UDPServerRun 514
          $UDPServerAddress 127.0.0.1
      notify:
        - restart syslog

    - name: place rsyslog config for haproxy
      copy:
        src: files/haproxy.conf
        dest: /etc/rsyslog.d
      notify:
        - restart syslog

  post_tasks:
    - name: open iRODS proxy port
      lineinfile:
        path: /etc/sysconfig/iptables
        line: -A INPUT -m state --state NEW -p tcp -s {{ load_balancer_irods_allowed_src }} --dport {{ load_balancer_irods_proxy_port }} -j ACCEPT
        insertbefore: -A INPUT -j REJECT
      notify:
        - restart firewall

  handlers:
    - name: reload haproxy
      service:
        name: haproxy
        state: reloaded

    - name: restart firewall
      service:
        name: iptables
        state: restarted

    - name: restart syslog
      service:
        name: rsyslog
        state: restarted

# TODO Learn about performance tuning
