---
- name: install HAPRoxy
  hosts: load_balancer
  become: true
  roles:
    - role: uoi-io.haproxy
      vars:
        haproxy_firewalld: false
        haproxy_selinux: false
        haproxy_global_maxconn: 256
        haproxy_global_tunes: []
        haproxy_default_errorfiles: []
        haproxy_default_maxconn: 32
        haproxy_default_mode: tcp
        haproxy_default_options:
          - dontlognull
        haproxy_default_timeouts:
          - connect 5000ms
          - client 50000ms
          - server 50000ms
        haproxy_stats: false
        haproxy_listen:
          - irods:
              binds:
                - "*:{{ load_balancer_irods_proxy_port }}"
              servers:
                - "{{ groups['ies'][0] }} {{ lookup('dig', groups['ies'][0]) }}:1247"

  tasks:
    - name: open iRODS proxy port
      lineinfile:
        path: /etc/sysconfig/iptables
        line: -A INPUT -m state --state NEW -p tcp -s {{ load_balancer_irods_allowed_src }} --dport {{ load_balancer_irods_proxy_port }} -j ACCEPT
        insertbefore: -A INPUT -j REJECT
      notify:
        - restart firewall

  handlers:
    - name: restart firewall
      service:
        name: iptables
        state: restarted

# TODO Learn about security considerations
# TODO configure haproxy to log to /var/log/haproxy.log
# TODO Learn about performance tuning
# TODO figure out timeouts
# TODO Tune maxconn for global and service
