---
- name: determine OS version
  hosts: rs:!ies:!unmanaged_systems
  tasks:
    - name: group by OS version
      group_by:
        key: centos{{ ansible_distribution_major_version }}

- name: install resource package on CentOS 6 resource servers
  hosts: centos6
  become: true
  tasks:
  - include: tasks/proxy_install.yml os=centos6 pkg=irods-resource

- name: install resource package on CentOS 7 resource servers
  hosts: centos7
  become: true
  tasks:
  - include: tasks/proxy_install.yml os=centos6 pkg=irods-resource
