---
- name: determine the iRODS servers that are on a physical machines
  hosts: irods
  become: true
  gather_facts: true
  tasks:
    - name: group by virtualization type
      group_by: 
        key: "{{ 'physical' if ansible_virtualization_type == 'NA' else '' }}"

    - name: group by managed
      group_by:
        key: "{{ 'managed' if manage_system else '' }}"

- name: determine the NIC throughput for the physical servers
  hosts: physical
  become: true
  gather_facts: false
  tasks:
    - name: call ethtool
      shell: "ethtool {{ ansible_default_ipv4.alias }} | sed -n 's/\tSpeed: \\([0-9]*\\).*/\\1/p'"
      register: ethtool
      changed_when: false

    - name: group by NIC speed
      group_by: 
        key: "{{ 'rs_10G' if ethtool.stdout|int >= 10000 else
                 'rs_1G'  if ethtool.stdout|int >= 1000 else '' }}"

- name: tune networking
  hosts: physical:&managed
  become: true
  gather_facts: false
  roles:
    - role: cyverse.ip
      ip_link_txqueuelen: "{{ nic_txqueuelen }}"

  tasks:
    - name: configure linux kernel 
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      with_items: "{{ sysctl }}"

- name: configure AMQP broker
  hosts: rabbitmq
  become: true
  gather_facts: false
  roles:
    - role: cyverse.rabbitmq-vhost
      rabbitmq_vhost_name: "{{ rabbitmq_vhost }}"
      rabbitmq_vhost_users: 
        - name: "{{ rabbitmq_user }}"
          configure_priv: .*
          write_priv: .*
          read_priv: .*

- include: mk_vaults.yml

- name: Install pika
  hosts: irods
  become: true
  tasks:
    - name: ensure pika installed
      pip:
        name: pika
        state: latest

- include: cfg_irods.yml
