---
- name: determine managed servers
  hosts: all
  gather_facts: false
  tasks:
    - name: group by managed
      group_by:
        key: "{{ 'managed' if manage_system else '' }}"

- name: create iRODS vaults
  hosts: rs:&managed
  become: true
  tasks:
    - name: create vaults directory
      when: manage_system
      with_items: "{{ irods_vaults }}"
      file:
        path: "{{ item }}"
        owner: "{{ irods_sys_user }}"
        group: "{{ irods_sys_user }}"
        state: directory

