---
- name: create iRODS vaults
  hosts: rs
  become: true
  tasks:
    - name: create vaults directory
      with_items: "{{ irods_vaults }}"
      file:
        path: "{{ item }}"
        owner: "{{ irods_sys_user }}"
        group: "{{ irods_sys_user }}"
        state: directory

