---
- name: create iRODS vaults
  hosts: rs:!unmanaged_systems
  become: true
  tasks:
    - name: create vaults directory
      with_items: "{{ irods_resources }}"
      file:
        path: "{{ item.vault }}"
        owner: "{{ irods_sys_user }}"
        group: "{{ irods_sys_user }}"
        state: directory

