---
- name: group managed systems
  hosts: all
  tasks:
    - name: group by managed
      group_by:
        key: "{{ 'managed' if manage_system else '' }}"

- name: Update /etc/hosts
  hosts: irods:&managed
  become: true
  gather_facts: false
  tasks:
    - name: update /etc/hosts
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
