---
- name: install dmidecode required by ansible gather_facts
  hosts: all:!unmanaged_systems
  become: true
  gather_facts: false
  tasks:
    - name: install dmidecode support
      package:
        name: dmidecode
        state: present


- name: install required packages for ansible
  hosts: all:!unmanaged_systems
  become: true
  tasks:
    - name: install EPEL repo
      when: ansible_distribution == 'CentOS'
      package:
        name: epel-release
        state: present

    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - jq
        - python-pip
        - python-requests
        - python-virtualenv
        - "{{ 'python-selinux' if ansible_distribution == 'Debian' else 'libselinux-python' }}"
