---
- name: install dmidecode required by ansible gather_facts
  hosts: all:!unmanaged_systems
  become: true
  gather_facts: false
  tasks:
    - name: install dmidecode support
      package:
        name: dmidecode
        state: present

- name: install required packages for ansible
  hosts: all:!unmanaged_systems
  become: true
  tasks:
    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - jq
        - openssl
        - python-pip
        - python-requests
        - python-virtualenv
        - "{{ 'python-selinux' if ansible_distribution == 'Debian' else 'libselinux-python' }}"

    - name: install packages on distributions other than CentOS 7 for pyOpenSSL install
      when: |
        ansible_distribution == 'Debian' or
        ansible_distribution == 'CentOS' and ansible_distribution_major_version|int < 7
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - gcc
        - "{{ 'libffi-dev' if ansible_distribution == 'Debian' else 'libffi-devel' }}"
        - "{{ 'libssl-dev' if ansible_distribution == 'Debian' else 'openssl-devel' }}"
        - "{{ 'python-dev' if ansible_distribution == 'Debian' else 'python-devel' }}"

    - name: upgrade setuptools on distributions other than CentOS 7 for pyOpenSSL install
      when: |
        ansible_distribution == 'Debian' or
        ansible_distribution == 'CentOS' and ansible_distribution_major_version|int < 7
      pip:
        name: setuptools
        version: 18.5

    - name: install pyOpenSSL
      pip:
        name: pyOpenSSL
