---
- name: upgrade system packages
  hosts: all:!unmanaged_systems
  become: true
  tasks:
    - name: ensure e2fsprogs is never updated by yum
      when: not _update_e2fsprogs
      lineinfile:
        name: /etc/yum.conf
        line: exclude=e2fsprogs.*

    - when: _rebootable
      block:
        - name: remove urllib3
          when: ansible_distribution_major_version == '6'
          pip:
            name: urllib3
            state: absent

        - name: upgrade system packages
          package:
            name: '*'
            state: latest
