---
- name: configure iRODS
  hosts: irods
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  tasks:
    - name: initialize flag
      set_fact:
        irods_cfg_made_changes: false

    - include_tasks: tasks/cfg_irods.yml

  post_tasks:
    - when: _restart_irods and irods_cfg_made_changes
      import_tasks: tasks/restart_irods.yml

  handlers:
    - name: reload rules
      file:
        path: /etc/irods/core.re
        state: touch


- name: configure bisque client
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  gather_facts: false
  tasks:
    - name: install bisque_paths.py
      get_url:
        validate_certs: no
        url: https://gitlab.cyverse.org/ds/bisque_support/raw/master/bisque_paths/bisque_paths.py
        dest: /var/lib/irods/iRODS/server/bin/cmd
        mode: u+wx
        force: true
      tags:
        # This may not be needed in ansible 2.5
        - non_idempotent

    - name: remove bisque_ops.py
      file:
        path: /var/lib/irods/iRODS/server/bin/cmd/bisque_ops.py
        state: absent

    - name: place .bisque
      when: _bisque_url is defined
      template:
        src: templates/bisque.j2
        dest: "{{ ansible_env.HOME }}/.bisque"
        mode: u=r
