---
- name: configure iRODS
  hosts: irods
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  tasks:
    - name: initialize flag
      set_fact:
        irods_cfg_made_changes: false

    - include_tasks: tasks/cfg_irods.yml

    - name: add common command scripts
      copy:
        src: "{{ item }}"
        dest: /var/lib/irods/iRODS/server/bin/cmd
        mode: u+x
      with_fileglob:
        - "files/cmd-common/*"

    - name: place static config in /etc/irods
      copy:
        src: "{{ item }}"
        dest: /etc/irods/{{ item | basename }}
        mode: u+r
      with_fileglob:
        - "files/etc/*"
      notify:
        - reload rules

    - name: place dynamic rule bases in /etc/irods
      template:
        src: "{{ item }}"
        dest: /etc/irods/{{ item | basename | regex_replace('.j2$') }}
        mode: u+r
      with_fileglob:
        - "templates/etc/*"
      notify:
        - reload rules

  post_tasks:
    - when: _restart_irods and irods_cfg_made_changes
      import_tasks: tasks/restart_irods.yml

  handlers:
    - name: reload rules
      file:
        path: /etc/irods/core.re
        state: touch


- name: Install AMQP publishing script
  hosts: ies
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  gather_facts: false
  tasks:
    - import_tasks: tasks/install_amqptopicsend.yml


- name: configure bisque client
  hosts: ies
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  gather_facts: false
  tasks:
    - name: install bisque_paths.py
      get_url:
        validate_certs: no
        url: https://gitlab.cyverse.org/ds/bisque_support/raw/master/bisque_paths/bisque_paths.py
        dest: /var/lib/irods/iRODS/server/bin/cmd
        mode: u=rx
        force: true
      tags:
        # This may not be needed in ansible 2.5
        - non_idempotent

    - name: remove bisque_ops.py
      file:
        path: /var/lib/irods/iRODS/server/bin/cmd/bisque_ops.py
        state: absent

    - name: place .bisque
      when: _bisque_url is defined
      template:
        src: templates/bisque.j2
        dest: "{{ ansible_env.HOME }}/.bisque"
        mode: u=r


- name: set minimum free space for resource
  hosts: rs
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  gather_facts: false
  tasks:
    - name: set context
      with_items: "{{ _irods_storage_resources }}"
      shell: |
        if ! currentContext=$(iadmin lr '{{ item.name }}' | sed --quiet 's/^resc_context: //p')
        then
          exit 1
        fi

        if [ '{{ item.context }}' = "$currentContext" ]
        then
          exit 0
        fi

        if ! iadmin modresc '{{ item.name }}' context '{{ item.context }}'
        then
          exit 1
        fi

        freeSpace=$(df --portability --block-size 1 '{{ item.vault }}' | tail -1 | awk '{ print $4 }')

        if [ "$?" -ne 0 ]
        then
          exit 1
        fi

        if ! iadmin modresc '{{ item.name }}' freespace "$freeSpace"
        then
          exit 1
        fi

        printf changed
      register: out
      changed_when: out.stdout == 'changed'
