---
- name: configure iRODS
  hosts: irods
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  tasks:
    - name: initialize flag
      set_fact:
        irods_cfg_made_changes: false

    - include_tasks: tasks/cfg_irods.yml

  post_tasks:
    - when: _restart_irods and irods_cfg_made_changes
      import_tasks: tasks/restart_irods.yml

  handlers:
    - name: reload rules
      file:
        path: /etc/irods/core.re
        state: touch
