---
- name: configure firewall for iRODS resource server
  hosts: rs:!unmanaged_systems
  become: true
  tasks:
    - name: configure firewall for inter server communication
      blockinfile:
        path: /etc/sysconfig/iptables
        insertbefore: -A INPUT -j REJECT
        marker: "# {mark} DS MANAGED BLOCK (iRODS inter-service)"
        content: |
          -A INPUT -m state --state NEW -p tcp -s {{ item }} --dport 1247 -j ACCEPT
          -A INPUT -m state --state NEW -p tcp -s {{ item }} --dport 1248 -j ACCEPT
          -A INPUT -m state --state NEW -p tcp -s {{ item }} --dport {{ _irods_server_port_range_start }}:{{ _irods_server_port_range_end }} -j ACCEPT
          -A INPUT -m state --state NEW -p udp -s {{ item }} --dport {{ _irods_server_port_range_start }}:{{ _irods_server_port_range_end }} -j ACCEPT
        notify:
          - restart firewall

    - name: configure firewall for clients
      blockinfile:
        path: /etc/sysconfig/iptables
        insertbefore: -A INPUT -j REJECT
        marker: "# {mark} DS MANAGED BLOCK (resource server:client)"
        content: |
          -A INPUT -m state --state NEW -p tcp -s {{ _irods_allowed_src }} --dport 1247 -j ACCEPT
          -A INPUT -m state --state NEW -p tcp -s {{ _irods_allowed_src }} --dport {{ _irods_server_port_range_start }}:{{ _irods_server_port_range_end }} -j ACCEPT
          -A INPUT -m state --state NEW -p udp -s {{ _irods_allowed_src }} --dport {{ _irods_server_port_range_start }}:{{ _irods_server_port_range_end }} -j ACCEPT
        notify:
          - restart firewall

- name: setup iRODS service account
  hosts: rs:!unmanaged_systems
  become: true
  gather_facts: false
  tasks:
    - name: create service group
      group:
        name: "{{ _irods_service_group_name }}"
        system: yes

    - name: create service account
      user:
        name: "{{ _irods_service_account_name }}"
        system: yes
        home: /var/lib/irods
        createhome: yes
        group: "{{ _irods_service_group_name }}"
        comment: iRODS Administrator

- import_playbook: mk_vaults.yml
- import_playbook: install_resource_pkg.yml
