---
- import_playbook: provision.yml


- name: install resource server package
  hosts: rs:!ies:!unmanaged_systems
  become: true
  gather_facts: false
  tasks:
    - import_tasks: tasks/install_resource_pkg.yml

    - import_tasks: tasks/install_plugins.yml


- import_playbook: cfg_irods.yml


- name: bootstrap iRODS start
  hosts: rs
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  gather_facts: false
  tasks:
    - name: initialize resource server connection to IES
      irods_clerver_auth:
        ies: "{{ groups['ies'][0] }}"
        password: "{{ _irods_clerver_password }}"

    - name: start iRODS
      irods_start:


- import_playbook: mk_storage_resources.yml
