---
# TODO implement
# - name: open firewall for iRODS

- name: setup iRODS service account
  hosts: rs:!unmanaged_systems
  become: true
  tasks:
    - name: create service group
      group:
        name: "{{ _irods_service_group_name }}"
        system: yes

    - name: create service account
      user:
        name: "{{ _irods_service_account_name }}"
        system: yes
        home: /var/lib/irods
        createhome: yes
        group: "{{ _irods_service_group_name }}"
        comment: iRODS Administrator

- import_playbook: mk_vaults.yml
- import_playbook: install_resource_pkg.yml
