---
- name: Customize for DE
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - name: create user for DE jobs
      when: _de_job_irods_user is defined
      irods_user:
        name: "{{ _de_job_irods_user }}"
        type: ds-service
        info: DE job
        password: ''

    - name: create jobs staging collection
      irods_collection:
        path: /{{ _irods_zone_name }}/jobs
