---
- name: create user for DE jobs
  hosts: ies
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - name: create account
      when: _de_job_irods_user is defined
      script: scripts/create-de-jobs-user.sh '{{ _de_job_irods_user }}'
      register: response
      changed_when: response.stdout == 'true'
