---
- name: initialize perms for rodsadmin
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  run_once: true
  tasks:
    - name: initialize perms
      script: scripts/init-rodsadmin-perms.sh '{{ groups['dbms'][0] }}' '{{ _dbms_port }}' '{{ _dbms_username }}' '{{ _irods_zone_name }}'
      register: response
      changed_when: response.stdout == 'true'
