---
- name: install uuidd
  hosts: irods:!unmanaged_systems
  become: true
  tasks:
    - name: install uuidd
      package:
        name: uuidd
        state: present

- name: install generateuuid.sh
  hosts: irods
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: install UUID generation cmd script
      get_url:
        url: https://raw.githubusercontent.com/cyverse/irods-cmd-scripts/master/generateuuid.sh
        dest: /var/lib/irods/iRODS/server/bin/cmd/generateuuid.sh
        mode: u=rx
