---
- name: determine os_version
  hosts: irods:!unmanaged_systems
  tasks:
    - name: group by OS version
      group_by:
        key: centos{{ ansible_distribution_major_version }}

  # For ansible 2.4.3 when a syntax-only run is performed this will generate a
  # warning because centos6 is a dynamically created group.
- name: install runtime package on CentOS 6 resource servers
  hosts: centos6
  become: true
  gather_facts: false
  tasks:
    - include_tasks: tasks/proxy_install.yml os=centos6 pkg=irods-runtime

  # For ansible 2.4.3 when a syntax-only run is performed this will generate a
  # warning because centos7 is a dynamically created group.
- name: install runtime package on CentOS 7 resource servers
  hosts: centos7
  become: true
  gather_facts: false
  tasks:
    - include_tasks: tasks/proxy_install.yml os=centos7 pkg=irods-runtime
