---
- name: determine os_version
  hosts: irods:!unmanaged_systems
  tasks:
    - name: group by OS version
      group_by:
        key: centos{{ ansible_distribution_major_version }}

- name: install runtime package on CentOS 6 resource servers
  hosts: centos6
  become: true
  tasks:
    - include: tasks/proxy_install.yml os=centos6 pkg=irods-runtime

- name: install runtime package on CentOS 7 resource servers
  hosts: centos7
  become: true
  tasks:
    - include: tasks/proxy_install.yml os=centos7 pkg=irods-runtime
