---
- name: run-time initialization
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  become_flags: '-i'
  run_once: true
  tasks:
    - name: ensure service user type exists
      irods_user_type:
        type: ds-service
        description: a Data Store service

    - name: ensure public group's home is correct
      irods_move:
        source: /{{ _irods_zone_name }}/home/public
        destination: /{{ _irods_zone_name }}/home/shared

    - name: ensure CyVerse curated collection base collection exists
      irods_collection:
        path: /{{ _irods_zone_name }}/home/shared/commons_repo/curated
        parents: true
        
    - name: initialize perms
      script: scripts/init-rodsadmin-perms.sh '{{ groups['dbms'][0] }}' '{{ _dbms_port }}' '{{ _dbms_username }}' '{{ _irods_zone_name }}'
      register: response
      changed_when: response.stdout == 'true'
      tags:
        - init_rodsadmin_perms

    - name: ensure anonymous user exists
      irods_user:
        name: anonymous

    - name: start quota usage computation
      command: irule '{ ipc_rescheduleQuotaUsageUpdate }' null ruleExecOut
      register: results
      changed_when: results.stdout == 'scheduled quota usage updates'
