---
- name: install HAPRoxy
  hosts: load_balancer
  become: true
  vars:
    server: "{{ groups['ies'][0] | regex_replace('\\..*') }}"
    server_ip: "{{ lookup('dig', groups['ies'][0]) }}"
  roles:
    - role: uoi-io.haproxy
      vars:
        haproxy_firewalld: false
        haproxy_selinux: false
        haproxy_global_cpu_maps:
          - 1 0
        haproxy_global_nbproc: 1
        haproxy_global_tunes: []
        haproxy_default_errorfiles: []
        haproxy_default_mode: tcp
        haproxy_default_options:
          - clitcpka
          - dontlognull
          - tcplog
        haproxy_default_timeouts:
          - connect 10s
          - client 1d
          - client-fin 2m
          - queue 10m
          - server 1d
          - server-fin 2m
        haproxy_stats: true
        haproxy_stats_address: '*'
        haproxy_stats_port: 80
        haproxy_stats_auth: false
        haproxy_stats_uri: /
        haproxy_stats_options:
          - refresh 10s
          - show-legends
          - hide-version
        haproxy_listen:
          - irods_main:
              binds:
                - :{{ load_balancer_irods_proxy_port }}
              servers:
                - "{{ server }} {{ server_ip }}:1247 maxconn {{ load_balancer_irods_max_conn }}"
          - irods_reconn:
              binds:
                - :{{ server_port_range_start }}-{{ server_port_range_end }}
              servers:
                - "{{ server }} {{ server_ip }}"
      notify:
        - reload haproxy

  pre_tasks:
    - name: configure rsyslog to listen on UDP socket
      blockinfile:
        path: /etc/rsyslog.conf
        insertafter: '# Provides UDP syslog reception'
        block: |
          $ModLoad imudp
          $UDPServerRun 514
          $UDPServerAddress 127.0.0.1
      notify:
        - restart syslog

    - name: place rsyslog config for haproxy
      copy:
        src: files/haproxy.conf
        dest: /etc/rsyslog.d
      notify:
        - restart syslog

  post_tasks:
    - name: configure firewall
      blockinfile:
        path: /etc/sysconfig/iptables
        insertbefore: -A INPUT -j REJECT
        marker: "# {mark} DS MANAGED BLOCK (load_balancer)"
        content: |
          -A INPUT -m state --state NEW -p tcp -s {{ load_balancer_irods_allowed_src }} --dport {{ load_balancer_irods_proxy_port }} -j ACCEPT
          -A INPUT -m state --state NEW -p tcp -s {{ load_balancer_irods_allowed_src }} --dport {{ server_port_range_start }}:{{ server_port_range_end }} -j ACCEPT
          -A INPUT -m state --state NEW -p tcp -s {{ load_balancer_stats_allowed_src }} --dport 80 -j ACCEPT
      notify:
        - restart firewall

  handlers:
    - name: reload haproxy
      service:
        name: haproxy
        state: reloaded

    - name: restart firewall
      service:
        name: iptables
        state: restarted

    - name: restart syslog
      service:
        name: rsyslog
        state: restarted
