---
- name: enable restarting of iRODS
  hosts: irods
  tasks:
    - set_fact:
        restart_irods: true


- name: configure AMQP broker
  hosts: rabbitmq
  become: true
  roles:
    - role: cyverse.rabbitmq-vhost
      rabbitmq_vhost_name: "{{ _rabbitmq_vhost }}"
      rabbitmq_vhost_users:
        - name: "{{ _rabbitmq_user }}"
          configure_priv: .*
          write_priv: .*
          read_priv: .*


- name: install pika
  hosts: ies
  become: true
  gather_facts: false
  tasks:
    - name: ensure pika installed
      pip:
        name: pika
        state: present


- import_playbook: provision.yml


- import_playbook: cfg_irods.yml


- name: start iRODS on IES
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  gather_facts: false
  tasks:
    - name: start iRODS
      irods_start:


- name: start iRODS on resource servers
  hosts: rs:!ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  gather_facts: false
  tasks:
    - name: start iRODS
      irods_start:


- name: run-time initialization
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  gather_facts: false
  run_once: true
  tasks:
    - name: ensure service user type exists
      shell: |
        desc=$(iquest \
          '%s' \
          "select TOKEN_VALUE2 where TOKEN_NAMESPACE = 'user_type' and TOKEN_NAME = 'ds-service'")
        exitCode="$?"

        if [ "$exitCode" -ne 0 ]
        then
          exit 1
        fi

        if ! [[ "$desc" =~ CAT_NO_ROWS_FOUND: ]]
        then
          exit 0
        fi

        if ! iadmin at user_type ds-service '' 'a Data Store service'
        then
          exit 1
        fi

        printf changed
      register: response
      changed_when: response.stdout == 'changed'

    - name: ensure public group's home is correct
      irods_move:
        source: /{{ _irods_zone_name }}/home/public
        destination: /{{ _irods_zone_name }}/home/shared

    - name: start quota usage computation
      command: irule '{ ipc_rescheduleQuotaUsageUpdate }' null ruleExecOut
      register: results
      changed_when: results.stdout == 'scheduled quota usage updates'


- import_playbook: de_usage.yml
