---
- name: configure AMQP broker
  hosts: rabbitmq
  become: true
  gather_facts: false
  roles:
    - role: cyverse.rabbitmq-vhost
      rabbitmq_vhost_name: "{{ _rabbitmq_vhost }}"
      rabbitmq_vhost_users:
        - name: "{{ _rabbitmq_user }}"
          configure_priv: .*
          write_priv: .*
          read_priv: .*

- name: Install pika
  hosts: ies
  become: true
  tasks:
    - name: ensure pika installed
      pip:
        name: pika
        state: present

- import_playbook: provision.yml
- import_playbook: cfg_irods.yml

- name: start quota usage computation
  hosts: ies
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  gather_facts: false
  tasks:
    - name: start computation
      run_once: true
      command: irule '{ ipc_rescheduleQuotaUsageUpdate }' null ruleExecOut
      register: results
      changed_when: results.stdout == 'scheduled quota usage updates'
