---
- name: create coordinating resources
  hosts: ies
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  run_once: true
  tasks:
    - irods_resource_hierarchy:
        hierarchy: "{{ item }}"
      with_items: "{{ _irods_resource_hierarchies }}"
