---
- name: create storage resources
  hosts: rs
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: create vault directory
      file:
        path: "{{ item.vault }}"
        follow: yes
        owner: "{{ _irods_service_account_name }}"
        group: "{{ _irods_service_group_name }}"
        mode: 'u=rwx'
        state: directory
      with_items: "{{ _irods_storage_resources }}"

    - name: define storage resource
      script: scripts/create-storage-resc.sh {{ item.name }} {{ inventory_hostname }} {{ item.vault }}
      with_items: "{{ _irods_storage_resources }}"
      register: result
      changed_when: result.stdout == 'changed'
