---
- name: provision IES
  hosts: ies
  become: true
  tasks:
    - name: ensure pika installed
      pip:
        name: pika
        state: present

    - name: configure linux kernel
      sysctl:
        name: kernel.{{ item.name }}
        value: "{{ item.value }}"
      with_items: "{{ _sysctl_kernel }}"
