---
- name: configure linux kernel on IES
  hosts: ies
  become: true
  tasks:
    - name: configure linux kernel
      sysctl:
        name: kernel.{{ item.name }}
        value: "{{ item.value }}"
      with_items: "{{ _sysctl_kernel }}"


- import_playbook: install_pika.yml
