---
- name: stop iRODS resource servers
  hosts: rs:!ies
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - import_tasks: tasks/stop_irods.yml

- name: restart IES
  hosts: ies
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: restart server
      command: /var/lib/irods/iRODS/irodsctl restart
  tags:
    - non_idempotent

- name: start resource servers
  hosts: rs:!ies
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  gather_facts: false
  tasks:
    - name: start servers
      command: /var/lib/irods/iRODS/irodsctl start
  tags:
    - non_idempotent
