---
- name: stop resource servers
  hosts: rs:!ies:!unmanaged_systems
  become: true
  tasks:
    - name: stop resource servers
      service:
        name: irods
        pattern: irodsServer
        state: stopped
      failed_when: false
  tags:
    - non_idempotent

- name: restart IES
  hosts: ies
  become: true
  tasks:
    - name: restart IES
      service:
        name: irods
        pattern: irodsServer
        state: restarted
  tags:
    - non_idempotent

- name: start resource servers
  hosts: rs:!ies:!unmanaged_systems
  become: true
  gather_facts: false
  tasks:
    - name: start resource servers
      service:
        name: irods
        pattern: irodsServer
        state: started
  tags:
    - non_idempotent
