---
- name: restart resource servers
  hosts: rs:!ies:!unmanaged_systems
  become: true
  tasks:
    - name: start resource servers again
      service:
        name: irods
        pattern: irodsServer
        state: restarted
  tags:
    - non_idempotent
