---
- name: stop iRODS resource servers
  hosts: rs:!ies
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - import_tasks: tasks/stop_irods.yml

- name: stop IES
  hosts: ies
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - import_tasks: tasks/stop_irods.yml
