---
- name: stop iRODS resource servers
  hosts: rs:!ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - import_tasks: tasks/stop_irods.yml

- name: stop IES
  hosts: ies
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - import_tasks: tasks/stop_irods.yml
