---
- import_playbook: stop_all.yml
  tags:
    # Because of the restart_all at the end, this task makes the playbook non-idempotent
    - non_idempotent


- name: begin IES upgrade
  hosts: ies:!unmanaged_systems
  become: true
  tasks:
    - import_tasks: tasks/install_ies_pkgs.yml


- name: upgrade resource server package
  hosts: rs:!ies:!unmanaged_systems
  become: true
  tasks:
    - import_tasks: tasks/install_resource_pkg.yml


- name: upgrade plugins
  hosts: irods:!unmanaged_systems
  become: true
  gather_facts: false
  tasks:
    - import_tasks: tasks/install_plugins.yml


- import_playbook: restart_all.yml
