---
- import_playbook: stop-all.yml
  tags:
    # Because of the restart-all at the end, this task makes the playbook non-idempotent
    - non_idempotent

- name: begin IES upgrade
  hosts: ies:!unmanaged_systems
  become: true
  vars:
    url_base: ftp://ftp.renci.org/pub/irods/releases/{{ _irods_version }}/centos6
    pg_rpm_ver: "{{ _irods_version | regex_replace('^4.', '') }}"
    pg_rpm: irods-database-plugin-postgres93-{{ pg_rpm_ver }}-centos6-x86_64.rpm
  tasks:
    - name: Download Database plugin package
      run_once: true
      delegate_to: localhost
      get_url:
        url: "{{ url_base }}/{{ pg_rpm }}"
        dest: /tmp

    - name: download iRODS PostgreSQL plugin package
      copy:
        src: /tmp/{{ pg_rpm }}
        dest: /root

    - name: upgrade database plugin
      yum:
        name: /root/{{ pg_rpm }}

    - include_tasks: tasks/proxy_install.yml os=centos6 pkg=irods-icat

- import_playbook: install_resource_pkg.yml
- import_playbook: install_runtime_pkg.yml

- name: Prepare for plugin upgrades
  hosts: irods:!unmanaged_systems
  tasks:
    - run_once: true
      delegate_to: localhost
      block:
        - name: checkout irods-netcdf-build repo
          git:
            repo: https://github.com/cyverse/irods-netcdf-build.git
            dest: /tmp/irods-netcdf-build
            version: "{{ _irods_version }}"

        - name: checkout msi-setavu-plugin repo
          git:
            repo: https://github.com/iPlantCollaborativeOpenSource/irods-setavu-plugin.git
            dest: /tmp/irods-setavu-plugin
            version: "{{ _irods_version }}"

        - name: build msiSetAVU plugin
          command: /tmp/irods-setavu-plugin/build
          tags:
            - no_testing

    - name: group by OS version
      group_by:
        key: centos{{ ansible_distribution_major_version }}

- name: Upgrade plugins on CentOS 6 servers
  hosts: centos6
  become: true
  gather_facts: false
  tasks:
    - include_tasks: tasks/upgrade_netcdf_plugins.yml repo_path=/tmp/irods-netcdf-build os=centos6

    - name: upgrade msiSetAVU microservice
      copy:
        src: /tmp/irods-setavu-plugin/libraries/centos6/libmsiSetAVU.so
        dest: /var/lib/irods/plugins/microservices/libmsiSetAVU.so
        force: yes
        owner: "{{ _irods_service_account_name }}"
        group: "{{ _irods_service_group_name }}"
  tags:
    - no_testing

- name: Upgrade plugins on CentOS 7 servers
  hosts: centos7
  become: true
  gather_facts: false
  tasks:
    - include_tasks: tasks/upgrade_netcdf_plugins.yml repo_path=/tmp/irods-netcdf-build os=centos7

    - name: upgrade msiSetAVU microservice
      copy:
        src: /tmp/irods-setavu-plugin/libraries/centos7/libmsiSetAVU.so
        dest: /var/lib/irods/plugins/microservices/libmsiSetAVU.so
        force: yes
        owner: "{{ _irods_service_account_name }}"
        group: "{{ _irods_service_group_name }}"
  tags:
    - no_testing

- import_playbook: restart-all.yml
