---
- import_playbook: stop_all.yml
  tags:
    # Because of the restart_all at the end, this task makes the playbook non-idempotent
    - non_idempotent


- name: begin IES upgrade
  hosts: ies:!unmanaged_systems
  become: true
  vars:
    os: centos{{ ansible_distribution_major_version }}
    pg_rpm: "{{ 'irods-database-plugin-postgres93' if ansible_distribution_major_version|int == 6 else
                'irods-database-plugin-postgres' }}"
    pg_rpm_ver: "{{ _irods_version | regex_replace('^4.') }}"
  tasks:
    - include_tasks: tasks/install_irods_pkg.yml pkg={{ pg_rpm }} pkg_ver={{ pg_rpm_ver }}
    - include_tasks: tasks/install_irods_pkg.yml pkg=irods-icat pkg_ver={{ _irods_version }}


- name: upgrade resource server package
  hosts: rs:!ies:!unmanaged_systems
  become: true
  tasks:
    - import_tasks: tasks/install_resource_pkg.yml


- name: upgrade plugins
  hosts: irods:!unmanaged_systems
  become: true
  gather_facts: false
  tasks:
    - import_tasks: tasks/install_plugins.yml


- import_playbook: restart_all.yml
