---
- import_playbook: stop_all.yml
  tags:
    # Because of the restart_all at the end, this task makes the playbook non-idempotent
    - non_idempotent

- name: begin IES upgrade
  hosts: ies:!unmanaged_systems
  become: true
  gather_facts: false
  vars:
    os: centos{{ ansible_distribution_major_version }}
    pg_rpm: "{{ 'irods-database-plugin-postgres93' if ansible_distribution_major_version == 6 else
                'irods-database-plugin-postgres' }}"
    pg_rpm_ver: "{{ _irods_version | regex_replace('^4.') }}"
  tasks:
    - include_tasks: tasks/proxy_install.yml pkg={{ pg_rpm }} pkg_ver={{ pg_rpm_ver }}
    - include_tasks: tasks/proxy_install.yml pkg=irods-icat pkg_ver={{ _irods_version }}

- import_playbook: install_resource_pkg.yml

- name: upgrade plugins
  hosts: irods:!unmanaged_systems
  become: true
  vars:
    os: centos{{ ansible_distribution_major_version }}
  tasks:
    - include_tasks: tasks/proxy_install.yml pkg=irods-runtime pkg_ver={{ _irods_version }}

    - name: checkout irods-netcdf-build repo
      run_once: true
      local_action:
        module: git
        repo: https://github.com/cyverse/irods-netcdf-build.git
        dest: /tmp/irods-netcdf-build
        version: "{{ _irods_version }}"

    - block:
        - name: build irods-netcdf plugins
          run_once: true
          local_action: command /tmp/irods-netcdf-build/build

        - include_tasks: tasks/upgrade_netcdf_plugins.yml repo_path=/tmp/irods-netcdf-build
      tags:
        # docker in docker is a no no.
        - no_testing

    - name: checkout msi-setavu-plugin repo
      run_once: true
      local_action:
        module: git
        repo: https://github.com/iPlantCollaborativeOpenSource/irods-setavu-plugin.git
        dest: /tmp/irods-setavu-plugin
        version: "{{ _irods_version }}"

    - block:
        - name: build msiSetAVU plugin
          run_once: true
          local_action: command /tmp/irods-setavu-plugin/build

        - name: upgrade msiSetAVU microservice
          copy:
            src: /tmp/irods-setavu-plugin/libraries/{{ os }}/libmsiSetAVU.so
            dest: /var/lib/irods/plugins/microservices/libmsiSetAVU.so
            force: yes
            owner: "{{ _irods_service_account_name }}"
            group: "{{ _irods_service_group_name }}"
      tags:
        # docker in docker is a no no.
        - no_testing

- import_playbook: restart_all.yml
