---
- name: install WebDAV server
  hosts: webdav
  become: true
  roles:
    - role: geerlingguy.apache
      vars:
        apache_ssl_cipher_suite: "HIGH:3DES:!aNULL:!MD5:!SEED:!IDEA"
        apache_global_vhost_settings: |
          LoadModule log_forensic_module_modules/mod_log_forensic.so
          LoadModule proxy_html_module modules/mod_proxy_html.so
          LoadModule unique_id_module modules/mod_unique_id.so

          ForensicLog "logs/forensic_log"

          CacheRoot {{ _webdav_cache_dir }}
          CacheDirLevels 2
          CacheDirLength 1
          CacheMaxFileSize {{ _webdav_cache_max_file_size }}
        apache_vhosts:
          - servername: "{{ inventory_hostname }}"
            extra_parameters: |
              Redirect permanent / https://{{ inventory_hostname }}/
            comment: Redirect HTTP to HTTPS
          - servername: 127.0.0.1
            listen_ip: 127.0.0.1
            extra_parameters: |
              CacheQuickHandler off
              CacheEnable disk /dav
              CacheLock on
              CacheLockPath /tmp/mod_cache-lock
              CacheLockMaxAge 5
              CacheHeader on
              CacheIgnoreHeaders Set-Cookie
              CacheLastModifiedFactor 0.5

              ExpiresActive on

              Header merge Cache-Control public
              Header set Access-Control-Allow-Headers "Range"
              Header set Access-Control-Allow-Methods "GET, HEAD, OPTIONS"
              Header set Access-Control-Allow-Origin "*"
            comment: The WebDAV host
            locations:
              - path: /dav/{{ _irods_zone_name }}/commons/community_released
                comment: Anonymous read-only access to the community released data
                extra_parameters: |
                  RedirectPermanent \
                    /dav/{{ _irods_zone_name }}/commons/community_released/commons_repo/curated \
                    /dav/{{ _irods_zone_name }}/commons/cyverse_curated

                  DirectoryIndex disabled

                  AuthType None

                  Require all granted

                  Dav davrods-nolocks

                  DavRodsEnvFile /etc/httpd/irods/irods_environment.json
                  DavRodsServer {{ _canonical_hostname }} {{ _canonical_irods_port }}
                  DavRodsZone {{ _irods_zone_name }}
                  DavRodsAnonymousMode On
                  DavRodsAnonymousLogin "anonymous" ""
                  DavRodsExposedRoot /{{ _irods_zone_name }}/home/shared
                  DavRodsRxBufferKbs 32768
                  DavRodsHtmlHead /etc/httpd/irods/community-head.html

                  CacheDefaultExpire 2592000
                  CacheMaxExpire 31536000

                  ExpiresDefault "access plus 10080 minutes"
              - path: /dav/{{ _irods_zone_name }}/commons/cyverse_curated
                comment: Anonymous read-only access to the data curated by CyVerse
                extra_parameters: |
                  DirectoryIndex disabled

                  AuthType None

                  Require all granted

                  Dav davrods-nolocks

                  DavRodsEnvFile /etc/httpd/irods/irods_environment.json
                  DavRodsServer {{ _canonical_hostname }} {{ _canonical_irods_port }}
                  DavRodsZone {{ _irods_zone_name }}
                  DavRodsAnonymousMode On
                  DavRodsAnonymousLogin "anonymous" ""
                  DavRodsExposedRoot /{{ _irods_zone_name }}/home/shared/commons_repo/curated
                  DavRodsRxBufferKbs 32768
                  DavRodsHtmlHead /etc/httpd/irods/curated-head.html

                  CacheDefaultExpire 2592000
                  CacheMaxExpire 31536000

                  ExpiresDefault "access plus 10080 minutes"
              - path: /dav/{{ _irods_zone_name }}/home
                comment: Authenticated read-write access to the home collection
                extra_parameters: |
                  RedirectPermanent /dav/{{ _irods_zone_name }}/home/shared \
                                    /dav/{{ _irods_zone_name }}/projects

                  <RequireAll)
                    Require expr \
                      %{REQUEST_URI} !~ m#^/dav/{{ _irods_zone_name }}/home(/[^/]*/?)?$# \
                      || %{REMOTE_USER} != "anonymous"

                    Require valid-user
                  </RequireAll>

                  DirectoryIndex disabled

                  AuthType Basic
                  AuthName CyVerse
                  AuthBasicProvider irods

                  Dav davrods-locallock

                  DavDepthInfinity on
                  DavRodsEnvFile /etc/httpd/irods/irods_environment.json
                  DavRodsServer {{ _canonical_hostname }} {{ _canonical_irods_port }}
                  DavRodsZone {{ _irods_zone_name }}
                  DavRodsExposedRoot Home
                  DavRodsHtmlHead /etc/httpd/irods/home-head.html

                  CacheDefaultExpire 604800
                  CacheMaxExpire 2592000

                  ExpiresDefault "access plus 1440 minutes"
              - path: /dav/{{ _irods_zone_name }}/projects
                comment: Authenticated read-write access to the project folders
                extra_parameters: |
                  DirectoryIndex disabled

                  AuthType Basic
                  AuthName CyVerse
                  AuthBasicProvider irods

                  Dav davrods-locallock

                  DavDepthInfinity on
                  DavRodsEnvFile /etc/httpd/irods/irods_environment.json
                  DavRodsServer {{ _canonical_hostname }} {{ _canonical_irods_port }}
                  DavRodsZone {{ _irods_zone_name }}
                  DavRodsExposedRoot /{{ _irods_zone_name }}/home/shared
                  DavRodsHtmlHead /etc/httpd/irods/projects-head.html

                  CacheDefaultExpire 604800
                  CacheMaxExpire 2592000

                  ExpiresDefault "access plus 1440 minutes"
        apache_vhosts_ssl:
          - servername: "{{ inventory_hostname }}"
            certificate_file: "{{ _webdav_tls_cert_file }}"
            certificate_key_file: "{{ _webdav_tls_key_file }}"
            certificate_chain_file: "{{ _webdav_tls_chain_file }}"
            extra_parameters: |
              ErrorLog logs/ssl_error_log

              CustomLog logs/ssl_access_log forensic
              CustomLog logs/ssl_request_log "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b %{forensic-id}n"

              LogLevel warn

              BrowserMatch "MSIE [2-5]" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0

              <If "%{HTTP:Range} == 'bytes=0-'">
                # Remove the range header if requesting the whole file so that the response will
                # still be cached.
                RequestHeader unset Range
              </If>
              <Elseif "-n %{HTTP:Range}">
                # To prevent davrods from crashing, tell it not to cache partial responses
                RequestHeader merge Cache-Control no-store
              </Elseif>

              ProxyPreserveHost On
              ProxyHTMLEnable On
              ProxyHTMLLinks a href
              ProxyHTMLLinks base href
            comment: This proxy handles TLS, corrects requests, enables caching, and anonymous access for XMLHttpRequests
            locations:
              - path: /dav
                extra_parameters: |
                  ProxyPass http://127.0.0.1:{{ apache_listen_port }}/dav
                  ProxyPassReverse http://127.0.0.1:{{ apache_listen_port }}/dav
              - path: /dav-anon
                extra_parameters: |
                  # The base64 encoding of anonymous is YW5vbnltb3Vz
                  RequestHeader set Authorization "Basic YW5vbnltb3Vz"

                  ProxyPass http://127.0.0.1:{{ apache_listen_port }}/dav
                  ProxyPassReverse http://127.0.0.1:{{ apache_listen_port }}/dav
                  ProxyHTMLURLMap '^(.*)/dav $1/dav-anon [R]'
        apache_vhosts_template: ../../templates/webdav/vhosts.conf.j2
      tags:
        - no_testing

  pre_tasks:
    - include_tasks: tasks/install_irods_pkg.yml
      vars:
        os: centos{{ ansible_distribution_major_version }}
        pkg: irods-icommands
        pkg_ver: "{{ _irods_version }}"

    - include_tasks: tasks/install_irods_pkg.yml
      vars:
        os: centos{{ ansible_distribution_major_version }}
        pkg: irods-runtime
        pkg_ver: "{{ _irods_version }}"

  post_tasks:
    - name: configure htcacheclean
      template:
        src: templates/webdav/htcacheclean.j2
        dest: /etc/sysconfig/htcacheclean
      notify:
        - restart htcacheclean
      tags:
        - no_testing

    - name: create apache systemd service dependencies directory
      file:
        path: /etc/systemd/system/httpd.service.requires
        recurse: true
        state: directory

    - name: ensure htcacheclean runs when apache run
      file:
        path: /etc/systemd/system/httpd.service.requires
        src: /usr/lib/systemd/system/htcacheclean.service
        state: link
      notify:
        - restart apache
      tags:
        - no_testing

    - name: install davrods
      yum:
        name: https://github.com/UtrechtUniversity/davrods/releases/download/4.1_1.4.1/davrods-4.1_1.4.1-1.el7.centos.x86_64.rpm
      notify:
        - restart apache
      tags:
        - no_testing

  handlers:
    - name: restart htcacheclean
      service:
        name: htcacheclean
        state: restarted

# TODO do the following
# Update the iRODS environemt file.
# Update iptables
