---
- name: install WebDAV server
  hosts: webdav
  become: true
  roles:
    - role: geerlingguy.apache
      vars:
        apache_ssl_cipher_suite: "HIGH:3DES:!aNULL:!MD5:!SEED:!IDEA"
        apache_vhosts_ssl:
          - servername: "{{ inventory_hostname }}"
            certificate_file: "{{ _webdav_tls_cert_file }}"
            certificate_key_file: "{{ _webdav_tls_key_file }}"
            certificate_chain_file: "{{ _webdav_tls_chain_file }}"
            locations:
              - dav_zone_location: commons/community_released
                irods_zone_root: home/shared
                location_redirect:
                  from: commons_repo/curated
                  to: commons/cyverse_curated
                authenticated: false
                client_cache_expire: 604800
                server_cache_default_expire: 2592000
                server_cache_max_expire: 31536000
                davrods_html_head: community-head.html
              - dav_zone_location: commons/cyverse_curated
                irods_zone_root: home/shared/commons_repo/curated
                authenticated: false
                client_cache_expire: 604800
                server_cache_default_expire: 2592000
                server_cache_max_expire: 31536000
                davrods_html_head: curated-head.html
              - dav_zone_location: home
                irods_zone_root: home
                location_redirect:
                  from: shared
                  to: projects
                authenticated: true
                client_cache_expire: 86400
                server_cache_default_expire: 604800
                server_cache_max_expire: 2592000
                davrods_html_head: home-head.html
              - dav_zone_location: projects
                irods_zone_root: projects
                authenticated: true
                client_cache_expire: 86400
                server_cache_default_expire: 604800
                server_cache_max_expire: 2592000
                davrods_html_head: projects-head.html
        apache_vhosts_template: ../../templates/vhosts.conf.j2
      tags:
        - no_testing

  pre_tasks:
    - include_tasks: tasks/install_irods_pkg.yml
      vars:
        os: centos{{ ansible_distribution_major_version }}
        pkg: irods-icommands
        pkg_ver: "{{ _irods_version }}"

    - include_tasks: tasks/install_irods_pkg.yml
      vars:
        os: centos{{ ansible_distribution_major_version }}
        pkg: irods-runtime
        pkg_ver: "{{ _irods_version }}"

  post_tasks:
    - name: configure htcacheclean
      template:
        src: templates/htcacheclean.j2
        dest: /etc/sysconfig/htcacheclean
      notify:
        - restart htcacheclean
      tags:
        - no_testing

    - name: create apache systemd service dependencies directory
      file:
        path: /etc/systemd/system/httpd.service.requires
        recurse: true
        state: directory

    - name: ensure htcacheclean runs when apache run
      file:
        path: /etc/systemd/system/httpd.service.requires
        src: /usr/lib/systemd/system/htcacheclean.service
        state: link
      notify:
        - restart apache
      tags:
        - no_testing

    - name: install davrods
      yum:
        name: https://github.com/UtrechtUniversity/davrods/releases/download/4.1_1.4.1/davrods-4.1_1.4.1-1.el7.centos.x86_64.rpm
      notify:
        - restart apache
      tags:
        - no_testing

  handlers:
    - name: restart htcacheclean
      service:
        name: htcacheclean
        state: restarted

# TODO do the following
# Update httpd vhost configuration to the way davrods.cyverse.org is currently
# Update the iRODS environemt file.
# Update iptables
