---
- name: install WebDAV server
  hosts: webdav
  become: true
  roles:
    - role: geerlingguy.apache
      vars:
        apache_global_vhost_settings: |
          LoadModule log_forensic_module_modules/mod_log_forensic.so
          LoadModule unique_id_module modules/mod_unique_id.so

          <IfModule log_forensic_module>
            ForensicLog /var/log/httpd/forensic_log
          </IfModule>

          <IfModule log_config_module>
            LogFormat "%h %t \"%r\" %>s %b %D %L %{forensic-id}n" forensic
            CustomLog "logs/access_log" forensic
          </IfModule>

          CacheRoot {{ _webdav_cache_dir }}
          CacheDirLevels 2
          CacheDirLength 1
          CacheMaxFileSize {{ _webdav_cache_max_file_size }}
      tags:
        - no_testing

  pre_tasks:
    - include_tasks: tasks/install_irods_pkg.yml
      vars:
        os: centos{{ ansible_distribution_major_version }}
        pkg: irods-icommands
        pkg_ver: "{{ _irods_version }}"

    - include_tasks: tasks/install_irods_pkg.yml
      vars:
        os: centos{{ ansible_distribution_major_version }}
        pkg: irods-runtime
        pkg_ver: "{{ _irods_version }}"

  post_tasks:
    - name: configure htcacheclean
      template:
        src: templates/htcacheclean.j2
        dest: /etc/sysconfig/htcacheclean
      notify:
        - restart htcacheclean
      tags:
        - no_testing

    - name: create apache systemd service dependencies directory
      file:
        path: /etc/systemd/system/httpd.service.requires
        recurse: true
        state: directory

    - name: ensure htcacheclean runs when apache run
      file:
        path: /etc/systemd/system/httpd.service.requires
        src: /usr/lib/systemd/system/htcacheclean.service
        state: link
      notify:
        - restart apache
      tags:
        - no_testing

    - name: install davrods
      yum:
        name: https://github.com/UtrechtUniversity/davrods/releases/download/4.1_1.4.1/davrods-4.1_1.4.1-1.el7.centos.x86_64.rpm
      notify:
        - restart apache
      tags:
        - no_testing

  handlers:
    - name: restart htcacheclean
      service:
        name: htcacheclean
        state: restarted

# TODO do the following
# Update httpd vhost configuration to the way davrods.cyverse.org is currently
# Update the iRODS environemt file.
# Update iptables
