---
nic_txqueuelen: 10000

sysctl:
  - name: net.core.default_qdisc
    value: fq
  - name: net.core.netdev_max_backlog
    value: 1000
  - name: net.core.rmem_max
    value: 67108864
  - name: net.core.wmem_max
    value: 67108864
  - name: net.ipv4.tcp_mtu_probing
    value: 1
  - name: net.ipv4.tcp_rmem
    value: 4096 87380 33554432
  - name: net.ipv4.tcp_wmem
    value: 4096 65536 33554432
