---
sysctl:
  - name: net.core.rmem_max      
    value: 16777216
  - name: net.core.wmem_max
    value: 16777216
  - name: net.ipv4.tcp_rmem
    value: 4096 65536 16777216
  - name: net.ipv4.tcp_wmem
    value: 4096 65536 16777216
