---
- name: upgrade system packages
  hosts: all:!unmanaged_systems
  become: true
  gather_facts: true
  tasks:
    - when: rebootable
      block:
        - name: remove urllib3
          pip:
           name: urllib3
           state: absent

        - name: upgrade system packages
          package:
            name: '*'
            state: latest
