---
- name: upgrade system packages
  hosts: all:!unmanaged_systems
  become: true
  gather_facts: true
  tasks:
    - name: upgrade system packages
      when: rebootable
      package:
        name: '*'
        state: latest
