# XXX - This is a bug in the git module. It will be fixed in ansible 2.7
- name: remove previous irods-netcdf-build repo
  file:
    name: "{{ _build_dir }}/irods-netcdf-build"
    state: absent
  tags:
    - non_idempotent

- name: checkout irods-netcdf-build repo
  git:
    repo: https://github.com/cyverse/irods-netcdf-build.git
    dest: "{{ _build_dir }}/irods-netcdf-build"
    version: "{{ _irods_version }}"
    force: true
  register: response

- name: build iRODS NetCDF plugins
  when: response is changed
  command: "{{ _build_dir }}/irods-netcdf-build/build"
  tags:
    # docker in docker is a no no.
    - no_testing

# XXX - This is a bug in the git module. It will be fixed in ansible 2.7
- name: remove previous msi-setavu-plugin repo
  file:
    name: "{{ _build_dir }}/irods-setavu-plugin"
    state: absent
  tags:
    - non_idempotent

- name: checkout msi-setavu-plugin repo
  git:
    repo: https://github.com/iPlantCollaborativeOpenSource/irods-setavu-plugin.git
    dest: "{{ _build_dir }}/irods-setavu-plugin"
    version: "{{ _irods_version }}"
    force: true
  register: response

- name: build msiSetAVU plugin
  when: response is changed
  command: "{{ _build_dir }}/irods-setavu-plugin/build"
  tags:
    # docker in docker is a no no.
    - no_testing
