---
- name: install uuidd
  when: inventory_hostname not in groups['unmanaged_systems']
  become: true
  package:
    name: uuidd
    state: present

- name: install generateuuid.sh
  become: "{{ false if ansible_user|default('') == _irods_service_account_name else true }}"
  become_user: "{{ _irods_service_account_name }}"
  copy:
    src: files/cmd-common/generateuuid.sh
    dest: /var/lib/irods/iRODS/server/bin/cmd/generateuuid.sh
    mode: u+x
