---
- include_tasks: install_irods_pkg.yml
  vars:
    os: centos{{ ansible_distribution_major_version }}
    pkg: irods-resource
    pkg_ver: "{{ _irods_version }}"

- name: ensure account owns /var/lib/irods
  file:
    path: /var/lib/irods
    owner: "{{ _irods_service_account_name }}"
    group: "{{ _irods_service_group_name }}"
    recurse: yes

- name: ensure account owns /etc/irods
  file:
    path: /etc/irods
    owner: "{{ _irods_service_account_name }}"
    group: "{{ _irods_service_group_name }}"
    recurse: yes
