---
- include_tasks: install_irods_pkg.yml
  vars:
    os: centos{{ ansible_distribution_major_version }}
    pkg: irods-runtime
    pkg_ver: "{{ _irods_version }}"

- delegate_to: localhost
  run_once: true
  become: false
  import_tasks: build_plugins.yml

- include_tasks: install_netcdf_plugin.yml
  vars:
    plugin: "{{ item }}"
    rpm: "{{ item }}-1.0-centos{{ ansible_distribution_major_version }}.rpm"
  with_items:
    - irods-api-plugin-netcdf
    - irods-icommands-netcdf
    - irods-microservice-plugin-netcdf
  tags:
    # docker in docker is a no no.
    - no_testing

- name: upgrade msiSetAVU microservice
  copy:
    src: "{{ _build_dir }}/irods-setavu-plugin/libraries/centos{{ ansible_distribution_major_version }}/libmsiSetAVU.so"
    dest: /var/lib/irods/plugins/microservices/libmsiSetAVU.so
    owner: "{{ _irods_service_account_name }}"
    group: "{{ _irods_service_group_name }}"
  tags:
    # docker in docker is a no no.
    - no_testing
