---
- name: verify that pika is installed
  shell: pip2.6 show pika
  changed_when: false

- name: install amqptopicsend.py
  copy:
    src: files/amqptopicsend.py
    dest: /var/lib/irods/iRODS/server/bin/cmd/
    owner: "{{ irods_service_account_name }}"
    group: "{{ irods_service_group_name }}"
