---
- name: check to see if {{ pkg }} is installed
  yum:
    list: "{{ pkg }}"
  register: result
  failed_when: false

- when: result.results is not defined or result.results|count == 0 or result.results[0].version|version_compare(pkg_ver, '<')
  block:
    - name: Download {{ pkg }} locally
      local_action:
        module: get_url
        url: ftp://ftp.renci.org/pub/irods/releases/{{ _irods_version }}/{{ os }}/{{ pkg }}-{{ pkg_ver }}-{{ os }}-x86_64.rpm
        dest: /tmp/{{ pkg }}-{{ pkg_ver }}-{{ os }}-x86_64.rpm

    - name: upload {{ pkg }} to server
      copy:
        src: /tmp/{{ pkg }}-{{ pkg_ver }}-{{ os }}-x86_64.rpm
        dest: /root/{{ pkg }}-{{ pkg_ver }}-{{ os }}-x86_64.rpm

    - name: install {{ pkg }}
      yum:
        name: /root/{{ pkg }}-{{ pkg_ver }}-{{ os }}-x86_64.rpm
