---
- name: check to see if package is installed
  yum:
    list: "{{ pkg }}"
  register: result

- when: result.results|count == 0 or result.results[0].version|version_compare(_irods_version, '<')
  block:
    - name: Download package locally
      run_once: true
      delegate_to: localhost
      get_url:
        url: ftp://ftp.renci.org/pub/irods/releases/{{ _irods_version }}/{{ os }}/{{ pkg }}-{{ _irods_version }}-{{ os }}-x86_64.rpm
        dest: /tmp

    - name: upload package to resource server
      copy:
        src: /tmp/{{ pkg }}-{{ _irods_version }}-{{ os }}-x86_64.rpm
        dest: /root

    - name: install package
      yum:
        name: /root/{{ pkg }}-{{ _irods_version }}-{{ os }}-x86_64.rpm
