---
- when: inventory_hostname in groups['rs'] | difference(groups['ies'])
  include_tasks: stop_irods.yml

- name: restart ICAT enabled servers
  when: inventory_hostname in groups['ies']
  irods_ctl:
    state: restarted

- name: start resource servers
  when: inventory_hostname in groups['rs'] | difference(groups['ies'])
  irods_ctl:
