---
- name: update free space estimate
  with_items: "{{ irods_storage_resources }}"
  shell: |
    if ! resc=$(iadmin lr '{{ item.name }}') || [ "$resc" = 'No rows found']
    then
      exit 1
    fi

    estFreeSpace=$(sed --quiet 's/free_space: //p' <<< "$resc")
    freeSpace=$(df --portability --block-size 1 '{{ item.vault }}' | tail -1 | awk '{ print $4 }')

    if [ "$freeSpace" = "$estFreeSpace" ]
    then
      exit 0
    fi

    if ! iadmin modresc '{{ item.name }}' freespace "$freeSpace"
    then
      exit 1
    fi

    printf changed
  register: out
  changed_when: out.stdout == 'changed'
