---
# Stops iRODS. The variable stop_irods_result holds the change value
- name: check if svc acnt exists
  shell: |
    if id --user {{ _irods_service_account_name }} &> /dev/null
    then
      printf exists
    else
      printf missing
    fi
  register: idResult
  changed_when: false

- name: stop server
  become_flags: '-i'
  become: "{{ _become_svc_acnt }}"
  when: idResult.stdout == 'exists'
  irods_ctl:
    state: stopped
  register: stop_irods_result
