---
- name: build iRODS NetCDF plugins
  run_once: true
  delegate_to: localhost
  command: "{{ repo_path }}/build {{ os }}"

- name: download NetCDF rpm
  copy:
    src: "{{ repo_path }}/packages/{{ os }}/{{ item }}-1.0-{{ os }}.rpm"
    dest: /root
    force: yes
  with_items:
    - irods-api-plugin-netcdf
    - irods-icommands-netcdf
    - irods-microservice-plugin-netcdf

# TODO Fix this. The following two tasks only need to be performed if the 
#      previous task caused a change
#
# The following twp tasks make each other non-idempotent

- name: remove old iRODS NetCDF packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - irods-microservice-plugin-netcdf
    - irods-icommands-netcdf
    - irods-api-plugin-netcdf
  tags:
    - non_idempotent

- name: install new NetCDF packages
  yum:
    name: /root/{{ item }}-1.0-{{ os }}.rpm
  with_items:
    - irods-api-plugin-netcdf
    - irods-icommands-netcdf
    - irods-microservice-plugin-netcdf
  tags:
    - non_idempotent
