---
version: "2.0"

services:
  amqp:
    image: rabbitmq:3.5-management

  dbms:
    build:
      context: dbms
      args:
        IRODS_RESOURCES: "$IRODS_RS6_NAME:$IRODS_RS6_HOST:$IRODS_VAULT $IRODS_RS7_NAME:$IRODS_RS7_HOST:$IRODS_VAULT"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
    tty: true

  ies:
    build:
      context: ies
      args:
        DBMS_HOST: "$DBMS_HOST"
        IRODS_DEFAULT_RESOURCE: "$IRODS_DEFAULT_RESOURCE"
        IRODS_HOST: "$IRODS_IES"
        IRODS_LAST_EPHEMERAL_PORT: $IRODS_LAST_EPHEMERAL_PORT
        IRODS_SCHEMA_VALIDATION: "$IRODS_SCHEMA_VALIDATION"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
    hostname: "$IRODS_IES"
    tty: true
    depends_on:
      - amqp
      - dbms

  rs_centos6:
    build:
      context: rs
      dockerfile: Dockerfile.centos6
      args:
        IRODS_DEFAULT_RESOURCE: "$IRODS_DEFAULT_RESOURCE"
        IRODS_DEFAULT_VAULT: "$IRODS_VAULT"
        IRODS_HOST: "$IRODS_RS6_HOST"
        IRODS_IES: "$IRODS_IES"
        IRODS_LAST_EPHEMERAL_PORT: $IRODS_LAST_EPHEMERAL_PORT
        IRODS_SCHEMA_VALIDATION: "$IRODS_SCHEMA_VALIDATION"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
    hostname: "$IRODS_RS6_HOST"
    tty: true
    depends_on:
      - ies

  rs_centos7:
    build:
      context: rs
      dockerfile: Dockerfile.centos7
      args:
        IRODS_DEFAULT_RESOURCE: "$IRODS_DEFAULT_RESOURCE"
        IRODS_DEFAULT_VAULT: "$IRODS_VAULT"
        IRODS_HOST: "$IRODS_RS7_HOST"
        IRODS_IES: "$IRODS_IES"
        IRODS_LAST_EPHEMERAL_PORT: $IRODS_LAST_EPHEMERAL_PORT
        IRODS_SCHEMA_VALIDATION: "$IRODS_SCHEMA_VALIDATION"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
    hostname: "$IRODS_RS7_HOST"
    tty: true
    depends_on:
      - ies
